.gitignore
README.md
samples/NBomber.Samples/NBomber.Samples.csproj
src/NBomber/NBomber.fsproj

- Added Reports folder to git ignore
- Squahed commits

 reports folder to Git ignore

---

src/NBomber/ScenarioRunner.fs

```
192:NBomber.Examples.CSharp alexkondrashov$ dotnet run
[09:21:38 INF] Test HTTP (https://github.com) with 100 concurrent users has started
[09:21:38 INF] warming up
[09:21:39 INF] starting test flows
[09:21:39 INF] wait 00:00:10 until the execution ends
[09:21:49 INF] stoping test flows
[09:21:50 INF] building report
[09:21:50 INF] Scenario: Test HTTP (https://github.com) with 100 concurrent users, execution time: 00:00:10
+----------+-------------------------------------------+-------------------+
| flows    | steps                                     | concurrent copies |
+----------+-------------------------------------------+-------------------+
| GET flow | 1 - GET github.com/VIP-Logic/NBomber html | 100               |
+----------+-------------------------------------------+----- …
```

Retrying Scenarion and print report to the console

---

examples/NBomber.Examples.CSharp/Scenarios/HttpScenario.cs
examples/NBomber.Examples.FSharp/Scenarios/HttpScenario.fs
src/NBomber/Errors.fs
src/NBomber/Reporting.fs
src/NBomber/ScenarioDsl.fs
src/NBomber/ScenarioRunner.fs

adding Assertions API

---

README.md

Corrected spelling and added spaces before parenthesis

Correct minor typos in README

---

src/NBomber/Domain/Domain.fs
src/NBomber/Infra/ScenarioRunner.fs

removing AssertionResults;
adding tabs and paddings;
style improvements

removing AssertionResults; adding tabs and paddings; style improvements

---

src/NBomber/Api/CSharp.fs
src/NBomber/Api/FSharp.fs
src/NBomber/Domain/Domain.fs
src/NBomber/Infra/AssertIntegration.fs

- Removing `NOT FOUND` case for Assertions
- Removing `Generic` case for test integration
- Rename `test` -> `check`
- No validation for unique names as there is separate task for this

Assertions Improvements

---

src/NBomber/Infra/Reporting.fs

Trying to fix calculating of RPS and exclude pause time

excluding pause from RPS calculation

---

src/NBomber/Domain/Errors.fs
src/NBomber/DomainServices/NBomberRunner.fs
src/NBomber/DomainServices/Validation.fs
tests/NBomber.IntegrationTests/Configuration/ParseJson.fs
tests/NBomber.IntegrationTests/Configuration/ValidateContext.fs
tests/NBomber.IntegrationTests/Configuration/config.json
tests/NBomber.IntegrationTests/NBomber.IntegrationTests.fsproj

validation rules for unique scenarios and unique steps within scenario; and for empty report file name

Validate name

---

src/NBomber/Contracts.fs
src/NBomber/DomainServices/Validation.fs
tests/NBomber.IntegrationTests/NBomber.IntegrationTests.fsproj
tests/NBomber.IntegrationTests/Response.fs
tests/NBomber.IntegrationTests/Result.fs

added constructor for Result OK
added property based test

adding overload constructor for Result Ok

---

examples/FSharp/FSharp.Examples/Program.fs
src/NBomber/DomainServices/Reporting/Report.fs
src/NBomber/DomainServices/Reporting/TxtReport.fs
src/NBomber/Infra/HtmlBuilder.fs

[12:27:59 INF] Scenario: 'test_youtube', Duration time: '00:00:20', RPS: '31', Concurrent Copies: '100'
+----------------------------+--------------------------------------------------------------------+
| step                       | details                                                            |
+----------------------------+--------------------------------------------------------------------+
| - name                     | GET html                                                           |
+----------------------------+--------------------------------------------------------------------+
| - request count            | all = 626 | OK = 626 | failed = 0                                  |
+----------------------------+------------------------------------------------------------------ …

adding assertions to txt version

---

examples/FSharp/FSharp.Examples/config.json
src/NBomber/Contracts.fs
src/NBomber/DomainServices/Reporting/MdReport.fs
src/NBomber/DomainServices/Reporting/Report.fs
src/NBomber/DomainServices/Validation.fs
src/NBomber/NBomber.fsproj

Hi,
this adds markdown report support. 
I'm not opinionated at all about content, so do all what you wish with it

Add Markdown reports #81

---

src/NBomber/Infra/HtmlBuilder.fs

* html encode step names
* rm accidentally added file

HTML encode step names (#128)

---

src/NBomber/Domain/Assertion.fs
src/NBomber/Domain/Errors.fs
src/NBomber/DomainServices/Validation.fs
tests/NBomber.IntegrationTests/Configuration/ValidateContext.fs
tests/NBomber.IntegrationTests/Scenario.fs

In order to terminate faster and not wait till the end of the execution, Assertions stepNames validation was added.

Assertions validation

---

src/NBomber/Infra/Dependency.fs
src/NBomber/NBomber.fsproj
tests/NBomber.IntegrationTests/Infra/MqttTests.fs

Fixed Mqtt tests (replaced InMemorySink on TestCorrelator)

Fixed Mqtt tests (replaced InMemorySink on TestCorrelator)

---

src/NBomber/DomainServices/Reporting/MdReport.fs
src/NBomber/DomainServices/Reporting/TxtReport.fs
tests/NBomber.IntegrationTests/NBomber.IntegrationTests.fsproj
tests/NBomber.IntegrationTests/Reporting/TextReportTests.fs

- fix missing newlines in markdown by multiple scenarios
- output transfer data only if available in md and txt
- add md and txt reports output tests

test report formats - optional transfer data output

---

src/NBomber/DomainServices/Reporting/ViewModels.fs

fixed html report - latency distribution per time unit #255

---

src/NBomber/Api/FSharp.fs
src/NBomber/Contracts.fs
src/NBomber/DomainServices/NBomberContext.fs
src/NBomber/Infra/Dependency.fs
tests/NBomber.IntegrationTests/NBomberContextTests.fs

Extracts a subrecord from NBomberContext with report relevant properties.
Would be handy for making a CE builder: https://github.com/PragmaticFlow/NBomber.FSharp/blob/main/test/NBomber.FSharp.Test/DslTest.fs#L344-L353

extract ReportContext

---

src/NBomber/Infra/Dependency.fs

fixes #279 
GetEntryAssembly in Dependency.fs

Fix null GetEntryAssembly

---

examples/FSharpDev/CustomReporting/CustomReporting.fs
src/NBomber/Contracts.fs
src/NBomber/Domain/DomainTypes.fs
src/NBomber/Domain/HintsAnalyzer.fs
src/NBomber/Domain/Scenario.fs
src/NBomber/Domain/Statistics.fs
src/NBomber/Domain/Step.fs
src/NBomber/DomainServices/Reporting/ViewModels.fs
src/NBomber/DomainServices/TestHost/TestHost.fs
tests/NBomber.IntegrationTests/HintsAnalyzerTests.fs
tests/NBomber.IntegrationTests/StatisticsTests.fs
tests/NBomber.IntegrationTests/StepTests.fs

- refactored stats: added int64 to track bytes and ticks
- added tests for stats

refactored stats

---

src/NBomber/DomainServices/TestHost/TestHostConsole.fs
src/NBomber/Infra/ProgressBar.fs

fixed progress bar for stopped scenario

---

examples/FSharpDev/CustomReporting/CustomReporting.fs
examples/FSharpDev/HelloWorld/HelloWorldExample.fs
src/NBomber/Configuration/Constants.fs
src/NBomber/Contracts.fs
src/NBomber/Domain/Statistics.fs
src/NBomber/Domain/Step.fs
tests/NBomber.IntegrationTests/StatisticsTests.fs
tests/NBomber.IntegrationTests/StepTests.fs

- set more accurate Histogram settings

---

src/NBomber/Domain/Errors.fs
src/NBomber/Domain/Scenario.fs
tests/NBomber.IntegrationTests/ScenarioTests.fs

closes #365
- add step validation
- add integration tests

add validation for ambiguous step definition

---

examples/CSharpProd/CSharpProd.csproj
examples/CSharpProd/DataFeed/DataFeedTest.cs
examples/CSharpProd/HttpTests/AdvancedHttpTest.cs
examples/CSharpProd/HttpTests/AdvancedHttpWithConfig.cs
examples/CSharpProd/HttpTests/SimpleHttpTest.cs
examples/CSharpProd/HttpTests/TracingHttp.cs
examples/CSharpProd/RealtimeReporting/InfluxDbReporting.cs
examples/CSharpProd/XUnit/XUnitTest.cs
examples/FSharpDev/CustomReporting/CustomReporting.fs
examples/FSharpProd/DataFeed/DataFeedTest.fs
examples/FSharpProd/FSharpProd.fsproj
examples/FSharpProd/HelloWorld/CustomSettingsExample.fs
examples/FSharpProd/HelloWorld/HelloWorldExample.fs
examples/FSharpProd/HttpTests/AdvancedHttpTest.fs
examples/FSharpProd/HttpTests/AdvancedHttpWithConfig.fs
examples/FSharpProd/HttpTests/SimpleHttpTest.fs
examples/FSharpProd/HttpTests/TracingHttp.fs
examples/FSharpProd/Logging/ElasticSearchLogging.fs
examples/FSharpProd/MongoDb/MongoDbTest.fs
examples/FSharpProd/Program.fs
examples/FSharpProd/RealtimeReporting/InfluxDbReporting.fs
examples/FSharpProd/XUnit/XUnitTest.fs
tests/NBomber.IntegrationTests/ClientFactoryTests.fs

migrate FSharpProd and CSharpProd example projects to use latest NBomber
Two issues to address in future commits:
* update code related processing stats in unit test
* update code data collection in influxdb

Issue #383 - First attempt at reving to new NBomber

---

src/NBomber/Domain/HintsAnalyzer.fs
tests/NBomber.IntegrationTests/HintsAnalyzerTests.fs

closes #362 Add hint for HintAnalyzer for the case when statistics has no status code

add StatusCodes hint analyzer

---

src/NBomber.Contracts/Stats.fs
src/NBomber/DomainServices/Reports/Report.fs
tests/NBomber.IntegrationTests/StatisticsTests.fs

Reports generation in-memory

---

src/NBomber/DomainServices/Reports/CsvReport.fs
tests/NBomber.IntegrationTests/NBomber.IntegrationTests.fsproj
tests/NBomber.IntegrationTests/Reporting/CSVReportingTests.fs

corrected formatting with newline between scenarios in the csv reporter
